version: '3'
services:
  java:
    build:
      context: ./wallet
      dockerfile: dockerfile
    environment:
      - JAVA_OPTS='-Djava.awt.headless=true'
    # volumes:
    #   - ./dependencies:/root/.m2
    ports:
      - "3000:3000"
    expose:
      - 3000
  db:
    build:
      context: ./database
      dockerfile: dockerfile
    restart: always
    environment:
      POSTGRES_DB: 'wallet_db'
      # # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'postgres'
      # You can use whatever password you like
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    # user: "1000:990" #user: "${UID}:${GID}"
    expose:
      - "5434"